dummy_demo_one/config/routes.rb
DummyDemoOne::Application.routes.draw do
  get "home/index"

  resources :micrroposts

  resources :miccroposts

  resources :micropossts

  resources :users

  root :to => 'home#index'

end

dummy_demo_one/app/models/micrropost.rb
class Micrropost < ActiveRecord::Base
  attr_accessible :content, :userid
end

dummy_demo_one/app/controllers/micrroposts_controller.rb
class MicrropostsController < ApplicationController
  # GET /micrroposts
  # GET /micrroposts.json
  def index
    @micrroposts = Micrropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @micrroposts }
    end
  end

  # GET /micrroposts/1
  # GET /micrroposts/1.json
  def show
    @micrropost = Micrropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micrropost }
    end
  end

  # GET /micrroposts/new
  # GET /micrroposts/new.json
  def new
    @micrropost = Micrropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micrropost }
    end
  end

  # GET /micrroposts/1/edit
  def edit
    @micrropost = Micrropost.find(params[:id])
  end

  # POST /micrroposts
  # POST /micrroposts.json
  def create
    @micrropost = Micrropost.new(params[:micrropost])

    respond_to do |format|
      if @micrropost.save
        format.html { redirect_to @micrropost, notice: 'Micrropost was successfully created.' }
        format.json { render json: @micrropost, status: :created, location: @micrropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micrropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /micrroposts/1
  # PUT /micrroposts/1.json
  def update
    @micrropost = Micrropost.find(params[:id])

    respond_to do |format|
      if @micrropost.update_attributes(params[:micrropost])
        format.html { redirect_to @micrropost, notice: 'Micrropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micrropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micrroposts/1
  # DELETE /micrroposts/1.json
  def destroy
    @micrropost = Micrropost.find(params[:id])
    @micrropost.destroy

    respond_to do |format|
      format.html { redirect_to micrroposts_url }
      format.json { head :no_content }
    end
  end
end

dummy_demo_one/app/helpers/micrroposts_helper.rb
module MicrropostsHelper
end

dummy_demo_one/app/views/micrroposts/_form.html.erb
<%= form_for(@micrropost) do |f| %>
  <% if @micrropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micrropost.errors.count, "error") %> prohibited this micrropost from being saved:</h2>

      <ul>
      <% @micrropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dummy_demo_one/app/views/micrroposts/edit.html.erb
<h1>Editing micrropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micrropost %> |
<%= link_to 'Back', micrroposts_path %>

dummy_demo_one/app/views/micrroposts/index.html.erb
<h1>Listing micrroposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Userid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @micrroposts.each do |micrropost| %>
  <tr>
    <td><%= micrropost.content %></td>
    <td><%= micrropost.userid %></td>
    <td><%= link_to 'Show', micrropost %></td>
    <td><%= link_to 'Edit', edit_micrropost_path(micrropost) %></td>
    <td><%= link_to 'Destroy', micrropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micrropost', new_micrropost_path %>

dummy_demo_one/app/views/micrroposts/new.html.erb
<h1>New micrropost</h1>

<%= render 'form' %>

<%= link_to 'Back', micrroposts_path %>

dummy_demo_one/app/views/micrroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micrropost.content %>
</p>

<p>
  <b>Userid:</b>
  <%= @micrropost.userid %>
</p>


<%= link_to 'Edit', edit_micrropost_path(@micrropost) %> |
<%= link_to 'Back', micrroposts_path %>