dummy_demo_one/config/routes.rb
DummyDemoOne::Application.routes.draw do
  get "home/index"

  resources :micrroposts

  resources :miccroposts

  resources :micropossts

  resources :users

  root :to => 'home#index'

end

dummy_demo_one/app/models/microposst.rb
class Microposst < ActiveRecord::Base
  attr_accessible :content, :user_id
end

dummy_demo_one/app/controllers/micropossts_controller.rb
class MicroposstsController < ApplicationController
  # GET /micropossts
  # GET /micropossts.json
  def index
    @micropossts = Microposst.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @micropossts }
    end
  end

  # GET /micropossts/1
  # GET /micropossts/1.json
  def show
    @microposst = Microposst.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @microposst }
    end
  end

  # GET /micropossts/new
  # GET /micropossts/new.json
  def new
    @microposst = Microposst.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @microposst }
    end
  end

  # GET /micropossts/1/edit
  def edit
    @microposst = Microposst.find(params[:id])
  end

  # POST /micropossts
  # POST /micropossts.json
  def create
    @microposst = Microposst.new(params[:microposst])

    respond_to do |format|
      if @microposst.save
        format.html { redirect_to @microposst, notice: 'Microposst was successfully created.' }
        format.json { render json: @microposst, status: :created, location: @microposst }
      else
        format.html { render action: "new" }
        format.json { render json: @microposst.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /micropossts/1
  # PUT /micropossts/1.json
  def update
    @microposst = Microposst.find(params[:id])

    respond_to do |format|
      if @microposst.update_attributes(params[:microposst])
        format.html { redirect_to @microposst, notice: 'Microposst was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @microposst.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micropossts/1
  # DELETE /micropossts/1.json
  def destroy
    @microposst = Microposst.find(params[:id])
    @microposst.destroy

    respond_to do |format|
      format.html { redirect_to micropossts_url }
      format.json { head :no_content }
    end
  end
end

dummy_demo_one/app/helpers/micropossts_helper.rb
module MicroposstsHelper
end

dummy_demo_one/app/views/micropossts/_form.html.erb
<%= form_for(@microposst) do |f| %>
  <% if @microposst.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@microposst.errors.count, "error") %> prohibited this microposst from being saved:</h2>

      <ul>
      <% @microposst.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dummy_demo_one/app/views/micropossts/edit.html.erb
<h1>Editing microposst</h1>

<%= render 'form' %>

<%= link_to 'Show', @microposst %> |
<%= link_to 'Back', micropossts_path %>

dummy_demo_one/app/views/micropossts/index.html.erb
<h1>Listing micropossts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @micropossts.each do |microposst| %>
  <tr>
    <td><%= microposst.content %></td>
    <td><%= microposst.user_id %></td>
    <td><%= link_to 'Show', microposst %></td>
    <td><%= link_to 'Edit', edit_microposst_path(microposst) %></td>
    <td><%= link_to 'Destroy', microposst, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Microposst', new_microposst_path %>

dummy_demo_one/app/views/micropossts/new.html.erb
<h1>New microposst</h1>

<%= render 'form' %>

<%= link_to 'Back', micropossts_path %>

dummy_demo_one/app/views/micropossts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @microposst.content %>
</p>

<p>
  <b>User:</b>
  <%= @microposst.user_id %>
</p>


<%= link_to 'Edit', edit_microposst_path(@microposst) %> |
<%= link_to 'Back', micropossts_path %>