dummy_demo_one/config/routes.rb
DummyDemoOne::Application.routes.draw do
  get "home/index"

  resources :micrroposts

  resources :miccroposts

  resources :micropossts

  resources :users

  root :to => 'home#index'

end

dummy_demo_one/app/models/miccropost.rb
class Miccropost < ActiveRecord::Base
  attr_accessible :content, :userid
end

dummy_demo_one/app/controllers/miccroposts_controller.rb
class MiccropostsController < ApplicationController
  # GET /miccroposts
  # GET /miccroposts.json
  def index
    @miccroposts = Miccropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @miccroposts }
    end
  end

  # GET /miccroposts/1
  # GET /miccroposts/1.json
  def show
    @miccropost = Miccropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @miccropost }
    end
  end

  # GET /miccroposts/new
  # GET /miccroposts/new.json
  def new
    @miccropost = Miccropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @miccropost }
    end
  end

  # GET /miccroposts/1/edit
  def edit
    @miccropost = Miccropost.find(params[:id])
  end

  # POST /miccroposts
  # POST /miccroposts.json
  def create
    @miccropost = Miccropost.new(params[:miccropost])

    respond_to do |format|
      if @miccropost.save
        format.html { redirect_to @miccropost, notice: 'Miccropost was successfully created.' }
        format.json { render json: @miccropost, status: :created, location: @miccropost }
      else
        format.html { render action: "new" }
        format.json { render json: @miccropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /miccroposts/1
  # PUT /miccroposts/1.json
  def update
    @miccropost = Miccropost.find(params[:id])

    respond_to do |format|
      if @miccropost.update_attributes(params[:miccropost])
        format.html { redirect_to @miccropost, notice: 'Miccropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @miccropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miccroposts/1
  # DELETE /miccroposts/1.json
  def destroy
    @miccropost = Miccropost.find(params[:id])
    @miccropost.destroy

    respond_to do |format|
      format.html { redirect_to miccroposts_url }
      format.json { head :no_content }
    end
  end
end

dummy_demo_one/app/helpers/miccroposts_helper.rb
module MiccropostsHelper
end

dummy_demo_one/app/views/miccroposts/_form.html.erb
<%= form_for(@miccropost) do |f| %>
  <% if @miccropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@miccropost.errors.count, "error") %> prohibited this miccropost from being saved:</h2>

      <ul>
      <% @miccropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :userid %><br />
    <%= f.number_field :userid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dummy_demo_one/app/views/miccroposts/edit.html.erb
<h1>Editing miccropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @miccropost %> |
<%= link_to 'Back', miccroposts_path %>

dummy_demo_one/app/views/miccroposts/index.html.erb
<h1>Listing miccroposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Userid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @miccroposts.each do |miccropost| %>
  <tr>
    <td><%= miccropost.content %></td>
    <td><%= miccropost.userid %></td>
    <td><%= link_to 'Show', miccropost %></td>
    <td><%= link_to 'Edit', edit_miccropost_path(miccropost) %></td>
    <td><%= link_to 'Destroy', miccropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Miccropost', new_miccropost_path %>

dummy_demo_one/app/views/miccroposts/new.html.erb
<h1>New miccropost</h1>

<%= render 'form' %>

<%= link_to 'Back', miccroposts_path %>

dummy_demo_one/app/views/miccroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @miccropost.content %>
</p>

<p>
  <b>Userid:</b>
  <%= @miccropost.userid %>
</p>


<%= link_to 'Edit', edit_miccropost_path(@miccropost) %> |
<%= link_to 'Back', miccroposts_path %>